spring:
  application:
    name: nacos-test

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      server-addr: ${spring.cloud.nacos.discovery.server-addr}
logging:
  level:
    com.gqz: debug
