server:
  port: 80


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://gqz2019.top:8090/eureka

  instance:
    hostname: gqz2019.top
    prefer-ip-address: true

spring:
  application:
    name: consumer